# Generated by Django 4.2.16 on 2024-09-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(default=10, max_length=20)),
                ('group_attending', models.CharField(default='The Hub', max_length=200)),
                ('photo_consent', models.BooleanField(default=True)),
                ('addional_information', models.CharField(blank=True, max_length=700)),
                ('consent_letter', models.FileField(blank=True, upload_to='')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
    ]
