# Generated by Django 4.2.10 on 2024-02-27 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='consent',
        ),
        migrations.AddField(
            model_name='form',
            name='addional_information',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='form',
            name='age',
            field=models.CharField(default=10, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='consent_letter',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='form',
            name='group_attending',
            field=models.CharField(default='The Hub', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='photo_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
