# Generated by Django 4.2.10 on 2024-02-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='consent',
        ),
        migrations.AddField(
            model_name='form',
            name='addional_information',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='form',
            name='date_of_birth',
            field=models.DateField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='form',
            name='photo_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='trip_consent_letter',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
