# Generated by Django 4.2.10 on 2024-02-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='consent',
        ),
        migrations.AddField(
            model_name='form',
            name='addional_information',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='form',
            name='age',
            field=models.CharField(default=10, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='group_attending',
            field=models.CharField(default='The Hub', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='photo_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='trip_consent_letter',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
