# Generated by Django 4.2.10 on 2024-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(default=10, max_length=20)),
                ('group_attending', models.CharField(default='The Hub', max_length=200)),
                ('photo_consent', models.BooleanField(default=True)),
                ('addional_information', models.CharField(blank=True, max_length=700)),
                ('consent_letter', models.FileField(blank=True, upload_to='')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
