# Generated by Django 4.2.10 on 2024-02-28 18:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_remove_form_consent_form_addional_information_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='UploadForm',
        ),
    ]
