# Generated by Django 4.2.10 on 2024-02-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_form_consent_form_addional_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='form',
            name='age',
            field=models.CharField(default=10, max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='group_attending',
            field=models.CharField(default='The Hub', max_length=200),
        ),
    ]
