# Generated by Django 4.2.10 on 2024-07-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_uploadform_delete_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadform',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
