# Generated by Django 4.2.10 on 2024-06-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_form_uploadform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadform',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
    ]
