# Generated by Django 4.2.10 on 2024-02-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_first_name_form_your_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='your_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='your_last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='form',
            name='childs_name',
        ),
    ]
