# Generated by Django 4.2.10 on 2024-06-25 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('game_ideas', models.CharField(blank=True, max_length=700)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_form', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
