# Generated by Django 4.2.16 on 2024-09-07 14:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('game_ideas', models.TextField()),
                ('approved_by', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('updated_on', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addactivity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_on'],
            },
        ),
    ]
