# Generated by Django 4.2.10 on 2024-06-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityform',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
