# Generated by Django 4.2.10 on 2024-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_rename_first_name_activityform_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityform',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
