# Generated by Django 4.2.10 on 2024-07-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_alter_activityform_options_activityform_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityform',
            name='first_name',
            field=models.CharField(default='Pick a display name', max_length=200),
        ),
    ]
