# Generated by Django 4.2.10 on 2024-07-01 20:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activites', '0005_alter_activityform_game_ideas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityform',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='activityform',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='activity_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
